CREATE TABLE CARSERVICE(
id INT NOT NULL IDENTITY,
name VARCHAR(45) NOT NULL,
address VARCHAR(120) NOT NULL,
openingTime INT NULL,
closingTime INT NULL,
PRIMARY KEY (id));

CREATE TABLE MACHINE(
id INT NOT NULL IDENTITY,
namePiking VARCHAR(45) NOT NULL,
vin VARCHAR(19) NOT NULL,
releaseYear DATE NOT NULL,
color_id INT NULL,
mark_id INT NULL,
numberPassengerSeats INT NULL,
numberPassengerStanding INT NULL,
numberAxle INT NULL,
capacity INT NULL,
PRIMARY KEY (id));

CREATE TABLE COLOR(
id INT NOT NULL IDENTITY,
name VARCHAR(45) NOT NULL,
rgb VARCHAR(11) NOT NULL,
PRIMARY KEY (id));

CREATE TABLE MARK(
id INT NOT NULL IDENTITY,
manufacturer VARCHAR(45) NOT NULL,
PRIMARY KEY (id));

